import "./depyo_override.ts"
import fs from "node:fs/promises"
import path from "node:path"
// import PycDisassembler from "@depyo/PycDisassembler"
import { PycDecompiler } from "./pyarmor_call.ts"
import { loadFromOneshotSequenceFile } from "./pyarmor_marshal.ts"

const VERSION = "v0.5.0"

type CliArgs = {
  infile: string | null
  banner: boolean
}

function printUsage(execName: string): void {
  process.stderr.write(
    "This native executable is not for end users.\n" +
      "You should use the Python script `shot.py` instead.\n\n"
  )
  process.stderr.write(`Usage:  ${execName} [options] input.1shot.seq\n\n`)
  process.stderr.write("Options:\n")
  process.stderr.write("  --no-banner    Don't output banner\n")
  process.stderr.write("  --debug        Debug mode\n")
  process.stderr.write("  --version      Show version information and then exit\n")
  process.stderr.write("  --help         Show this help text and then exit\n")
}

function parseArgs(argv: string[]): CliArgs | number {
  let infile: string | null = null
  let banner = true

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!
    if (arg === "--help" || arg === "-h") {
      printUsage(process.argv[1] ?? "armorshot_depyo")
      return 0
    } else if (arg === "--version" || arg === "-v") {
      process.stdout.write(`${VERSION}\n`)
      return 0
    } else if (arg === "--no-banner") {
      banner = false
    } else if (arg === "--debug") {
      ;(global as any).g_cliArgs.debug = true
    } else if (arg.startsWith("-")) {
      process.stderr.write(`Error: Unrecognized argument ${arg}\n`)
      return 1
    } else if (infile === null) {
      infile = arg
    } else {
      process.stderr.write(`Error: Only one input file allowed, got ${infile} and ${arg}\n`)
      return 1
    }
  }

  if (infile === null) {
    process.stderr.write(
      "This native executable is not for end users.\n" +
        "You should use the Python script `shot.py` instead.\n\n"
    )
    process.stderr.write("No input file specified.\n")
    return 1
  }

  return { infile, banner }
}

function getPrefixName(infile: string): string {
  const marker = infile.indexOf(".1shot.seq")
  return marker === -1 ? infile : infile.slice(0, marker + 6)
}

// function buildDasBanner(dispname: string, major: number, minor: number): string {
//   return (
//     `# File: ${dispname} (Python ${major}.${minor})\n` +
//     `# Disassembly generated by Pyarmor-Static-Unpack-1shot (${VERSION}), powered by Depyo.js\n\n` +
//     "# ================================\n" +
//     "# Pyarmor notes:\n" +
//     "# - Pyarmor bytecode and code objects match standard Python, but special calls to Pyarmor runtime functions exist.\n" +
//     "# - Calls on strings are not mistakes but markers, which are processed by Pyarmor at runtime.\n" +
//     "#\n" +
//     "# Decompilation guidance (without runtime):\n" +
//     "# 1. Ignore encrypted bytes after `#`; use only the string before `#`.\n" +
//     '# 2. Remove "__pyarmor_enter_xxx__"(b"<COAddr>...") and "__pyarmor_leave_xxx__"(b"<COAddr>...") (prologue/epilogue).\n' +
//     '# 3. "__pyarmor_assert_xxx__"(A) is not a real assert statement.\n' +
//     "#    - If A is a name or readable string: replace with A.\n" +
//     '#    - If A is (X, "Y"): replace with X.Y.\n' +
//     '#    - If A is (X, "Y", Z): replace with X.Y = Z.\n' +
//     "#    - Otherwise: choose the most reasonable replacement.\n" +
//     '# 4. "__pyarmor_bcc_xxx__"(...) indicates native code; function body is not available. Add a comment.\n' +
//     "# ================================\n\n"
//   )
// }

function buildCdcBanner(
  dispname: string,
  major: number,
  minor: number,
  dispPrefix: string
): string {
  return (
    `# File: ${dispname} (Python ${major}.${minor})\n` +
    `# Source generated by Pyarmor-Static-Unpack-1shot (${VERSION}), powered by Depyo.js\n\n` +
    "# Note: Decompiled code can be incomplete and incorrect.\n" +
    `# Please also check the correct and complete disassembly file: ${dispPrefix}.das\n\n`
  )
}

async function main(): Promise<number> {
  const parsed = parseArgs(process.argv.slice(2))
  if (typeof parsed === "number") {
    return parsed
  }

  const infile = parsed.infile!
  const prefixName = getPrefixName(infile)
  const dcPath = `${prefixName}.cdc.py`
  // const dasPath = `${prefixName}.das`

  let reader
  let obj
  try {
    reader = await loadFromOneshotSequenceFile(infile)
    obj = reader.ReadObject()
  } catch (ex) {
    const msg = ex instanceof Error ? ex.message : String(ex)
    process.stderr.write(`Error disassembling ${infile}: ${msg}\n`)
    return 1
  }

  if (!obj) {
    process.stderr.write(`Could not load file ${infile}\n`)
    return 1
  }

  const major = reader.m_version.major
  const minor = reader.m_version.minor
  const dispname = path.basename(infile)
  const dispPrefix = path.basename(prefixName)

  // try {
  //   let dasContent = ""
  //   if (parsed.banner) {
  //     dasContent += buildDasBanner(dispname, major, minor)
  //   }
  //   dasContent += String(PycDisassembler.Disassemble(reader, obj, ""))
  //   await fs.writeFile(dasPath, dasContent)
  // } catch (ex) {
  //   const msg = ex instanceof Error ? ex.message : String(ex)
  //   process.stderr.write(`Error disassembling ${infile}: ${msg}\n`)
  //   return 1
  // }

  try {
    const decompiler = new PycDecompiler(obj)
    const ast = decompiler.decompile()
    const pysrc = String(ast.codeFragment())
    const cdcContent =
      (parsed.banner ? buildCdcBanner(dispname, major, minor, dispPrefix) : "") + pysrc
    await fs.writeFile(dcPath, cdcContent)
  } catch (ex) {
    const msg = ex instanceof Error ? ex.message : String(ex)
    process.stderr.write(`Error decompiling ${infile}: ${msg}\n`)
    return 1
  }

  return 0
}

const exitCode = await main().catch((ex: unknown) => {
  const msg = ex instanceof Error ? ex.message : String(ex)
  process.stderr.write(`Fatal error: ${msg}\n`)
  return 1
})
process.exit(exitCode)
